name: bg_fly
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  image_picker: ^1.1.2
  http: ^1.2.2
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  dotted_border: ^2.1.0
  remove_background: ^0.0.1
  media_scanner: ^2.1.0
  image_gallery_saver: ^2.0.3
  markdown: ^7.2.2
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.3.0

flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/preview.jpg
    - assets/logo.png
    - assets/logo-no-bg.png

 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
